bot-token:
server-id:
icon-storage:
  use: true
broadcaster:
  use: false
  channels: []
simple-forwarder:
  use: false
  channels: []
translator-forwarder:
  use: false
  channels: []
  languages:
    - en_US
    - ko_KR
group-linker:
  use: false
  groups:
    - discord minecraft